//! 声明式因子定义 — 所有 Alpha158 因子的元数据
//!
//! 每个因子由 name / name_cn / category / formula / window 组成。
//! 计算逻辑在 lib.rs 的 compute_factor() 中统一实现。

use crate::{FactorMeta, Category, Formula};

macro_rules! factor {
    ($name:expr, $cn:expr, $cat:ident, $formula:expr, $w:expr) => {
        FactorMeta {
            name: $name.into(),
            name_cn: $cn.into(),
            category: Category::$cat,
            formula: $formula,
            window: $w,
        }
    };
}

pub fn list_all() -> Vec<FactorMeta> {
    vec![
        // ═══════════════════ 趋势类 (Trend) 30个 ═══════════════════
        factor!("ma5", "5日均线偏离", Trend, Formula::MaDev(5), 5),
        factor!("ma10", "10日均线偏离", Trend, Formula::MaDev(10), 10),
        factor!("ma20", "20日均线偏离", Trend, Formula::MaDev(20), 20),
        factor!("ma60", "60日均线偏离", Trend, Formula::MaDev(60), 60),
        factor!("ma120", "120日均线偏离", Trend, Formula::MaDev(120), 120),
        factor!("ma5_dev", "5日均线Z-Score", Trend, Formula::MaZScore(5), 6),
        factor!("ma10_dev", "10日均线Z-Score", Trend, Formula::MaZScore(10), 11),
        factor!("ma20_dev", "20日均线Z-Score", Trend, Formula::MaZScore(20), 21),
        factor!("macd_dif", "MACD离差值", Trend, Formula::MacdDif, 26),
        factor!("macd_dea", "MACD信号线", Trend, Formula::MacdDea, 35),
        factor!("macd_hist", "MACD柱", Trend, Formula::MacdHist, 35),
        factor!("trix5", "三重指数平滑(5)", Trend, Formula::Trix(5), 16),
        factor!("trix10", "三重指数平滑(10)", Trend, Formula::Trix(10), 31),
        factor!("tr", "真实波幅", Trend, Formula::TrueRange, 2),
        factor!("atr5", "平均真实波幅(5)", Trend, Formula::Atr(5), 6),
        factor!("atr10", "平均真实波幅(10)", Trend, Formula::Atr(10), 11),
        factor!("atr20", "平均真实波幅(20)", Trend, Formula::Atr(20), 21),
        factor!("pdi", "上升动向(+DI)", Trend, Formula::Pdi(14), 15),
        factor!("mdi", "下降动向(-DI)", Trend, Formula::Mdi(14), 15),
        factor!("adx14", "趋向平均值(14)", Trend, Formula::Adx(14), 15),
        factor!("plrc5", "线性回归斜率(5)", Trend, Formula::Plrc(5), 5),
        factor!("plrc20", "线性回归斜率(20)", Trend, Formula::Plrc(20), 20),
        factor!("hh5", "5日最高价", Trend, Formula::Hh(5), 5),
        factor!("ll5", "5日最低价", Trend, Formula::Ll(5), 5),
        factor!("hh20", "20日最高价", Trend, Formula::Hh(20), 20),
        factor!("ll20", "20日最低价", Trend, Formula::Ll(20), 20),
        factor!("price_chan5", "价格通道位置(5)", Trend, Formula::PriceChannel(5), 5),
        factor!("price_chan20", "价格通道位置(20)", Trend, Formula::PriceChannel(20), 20),
        factor!("high_low5", "5日高低振幅比", Trend, Formula::HighLow(5), 5),
        factor!("high_low20", "20日高低振幅比", Trend, Formula::HighLow(20), 20),

        // ═══════════════════ 反转类 (Reversal) 22个 ═══════════════════
        factor!("rsi6", "RSI(6)", Reversal, Formula::Rsi(6), 6),
        factor!("rsi12", "RSI(12)", Reversal, Formula::Rsi(12), 12),
        factor!("rsi24", "RSI(24)", Reversal, Formula::Rsi(24), 24),
        factor!("wr10", "威廉指标(10)", Reversal, Formula::Wr(10), 10),
        factor!("wr30", "威廉指标(30)", Reversal, Formula::Wr(30), 30),
        factor!("bb_upper", "布林上轨", Reversal, Formula::BbUpper(20), 20),
        factor!("bb_lower", "布林下轨", Reversal, Formula::BbLower(20), 20),
        factor!("bb_width", "布林带宽", Reversal, Formula::BbWidth(20), 20),
        factor!("bias5", "乖离率(5)", Reversal, Formula::Bias(5), 5),
        factor!("bias10", "乖离率(10)", Reversal, Formula::Bias(10), 10),
        factor!("bias20", "乖离率(20)", Reversal, Formula::Bias(20), 20),
        factor!("bias60", "乖离率(60)", Reversal, Formula::Bias(60), 60),
        factor!("cci5", "商品通道指数(5)", Reversal, Formula::Cci(5), 5),
        factor!("cci20", "商品通道指数(20)", Reversal, Formula::Cci(20), 20),
        factor!("kdj_j", "KDJ-J值", Reversal, Formula::Kdjj, 9),
        factor!("kdj_d", "KDJ-D值", Reversal, Formula::Kdjd, 9),
        factor!("ema_fast_slow", "快慢EMA比", Reversal, Formula::EmaFastSlow, 20),
        factor!("disparity5", "距离均线比(5)", Reversal, Formula::Disparity(5), 5),
        factor!("disparity10", "距离均线比(10)", Reversal, Formula::Disparity(10), 10),
        factor!("close_sma_ratio5", "收盘/均线比(5)", Reversal, Formula::Rs(5), 5),
        factor!("close_sma_ratio10", "收盘/均线比(10)", Reversal, Formula::Rs(10), 10),
        factor!("close_sma_ratio20", "收盘/均线比(20)", Reversal, Formula::Rs(20), 20),

        // ═══════════════════ 波动类 (Volatility) 26个 ═══════════════════
        factor!("std5", "5日标准差", Volatility, Formula::Std(5), 5),
        factor!("std20", "20日标准差", Volatility, Formula::Std(20), 20),
        factor!("std60", "60日标准差", Volatility, Formula::Std(60), 60),
        factor!("vol5", "5日波动率", Volatility, Formula::Vol(5), 5),
        factor!("vol20", "20日波动率", Volatility, Formula::Vol(20), 20),
        factor!("vol60", "60日波动率", Volatility, Formula::Vol(60), 60),
        factor!("vol_ratio", "波动率比(近远)", Volatility, Formula::VolRatio, 20),
        factor!("amplitude", "振幅", Volatility, Formula::Amplitude, 2),
        factor!("dvrat", "日波动率比", Volatility, Formula::Dvrat, 20),
        factor!("davol5", "日均成交量(5)", Volatility, Formula::DaVol(5), 5),
        factor!("davol20", "日均成交量(20)", Volatility, Formula::DaVol(20), 20),
        factor!("upvol", "上涨量比", Volatility, Formula::UpVol(20), 20),
        factor!("dnvol", "下跌量比", Volatility, Formula::DnVol(20), 20),
        factor!("vol_skew", "收益率偏度", Volatility, Formula::VolatilitySkew(20), 20),
        factor!("vol_kurt", "收益率峰度", Volatility, Formula::VolatilityKurt(20), 20),
        factor!("max_ret5", "5日最大收益", Volatility, Formula::MaxRet(5), 5),
        factor!("max_ret20", "20日最大收益", Volatility, Formula::MaxRet(20), 20),
        factor!("min_ret5", "5日最大亏损", Volatility, Formula::MinRet(5), 5),
        factor!("min_ret20", "20日最大亏损", Volatility, Formula::MinRet(20), 20),
        factor!("high_low_ratio", "高低价比", Volatility, Formula::HighLowRatio, 2),
        factor!("range5", "5日价格区间", Volatility, Formula::Range(5), 5),
        factor!("range20", "20日价格区间", Volatility, Formula::Range(20), 20),
        factor!("ulcer5", "Ulcer指数(5)", Volatility, Formula::Ulcer(5), 5),
        factor!("ulcer20", "Ulcer指数(20)", Volatility, Formula::Ulcer(20), 20),
        factor!("amplitude5", "5日平均振幅", Volatility, Formula::AvgAmplitude(5), 5),
        factor!("amplitude20", "20日平均振幅", Volatility, Formula::AvgAmplitude(20), 20),

        // ═══════════════════ 成交量类 (Volume) 28个 ═══════════════════
        factor!("vol5_ma5", "5日均量", Volume, Formula::Vma(5), 5),
        factor!("vol10_ma10", "10日均量", Volume, Formula::Vma(10), 10),
        factor!("vol20_ma20", "20日均量", Volume, Formula::Vma(20), 20),
        factor!("vol60_ma60", "60日均量", Volume, Formula::Vma(60), 60),
        factor!("vstd5", "5日量标准差", Volume, Formula::Vstd(5), 5),
        factor!("vstd20", "20日量标准差", Volume, Formula::Vstd(20), 20),
        factor!("vosc", "成交量震荡", Volume, Formula::Vosc, 20),
        factor!("obv", "能量潮", Volume, Formula::Obv, 2),
        factor!("vwap_dev", "VWAP偏离", Volume, Formula::VwapDev(20), 20),
        factor!("pv_corr5", "量价相关(5)", Volume, Formula::PvCorr(5), 5),
        factor!("pv_corr20", "量价相关(20)", Volume, Formula::PvCorr(20), 20),
        factor!("volume_ratio", "量比", Volume, Formula::VolumeRatioFactor, 5),
        factor!("volume_trend", "量趋势", Volume, Formula::VolumeTrend, 20),
        factor!("mfi14", "资金流量指数(14)", Volume, Formula::Mfi(14), 14),
        factor!("eom", "便利性指数", Volume, Formula::Eom, 2),
        factor!("force_index", "强力指数", Volume, Formula::ForceIndex, 2),
        factor!("ad", "集散指标", Volume, Formula::Ad, 2),
        factor!("cmf20", "蔡金资金流(20)", Volume, Formula::Cmf(20), 20),
        factor!("nvi", "负量指数", Volume, Formula::Nvi, 2),
        factor!("pvi", "正量指数", Volume, Formula::Pvi, 2),
        factor!("vpt", "量价趋势", Volume, Formula::VolPriceTrend, 20),
        factor!("tvma5", "换手率偏离(5)", Volume, Formula::TvMa(5), 5),
        factor!("tvma20", "换手率偏离(20)", Volume, Formula::TvMa(20), 20),
        factor!("upside_vol", "上攻量占比", Volume, Formula::UpsideVolume(20), 20),
        factor!("downside_vol", "下杀量占比", Volume, Formula::DownsideVolume(20), 20),
        factor!("vol_ratio5", "5日量比", Volume, Formula::VolumeRatioFactor, 5),
        factor!("vol_ratio20", "20日量比", Volume, Formula::VolumeRatioFactor, 20),
        factor!("eom20", "便利性指数均线", Volume, Formula::Eom, 20),

        // ═══════════════════ 动量类 (Momentum) 28个 ═══════════════════
        factor!("ret1", "1日收益率", Momentum, Formula::Ret(1), 2),
        factor!("ret5", "5日收益率", Momentum, Formula::Ret(5), 6),
        factor!("ret10", "10日收益率", Momentum, Formula::Ret(10), 11),
        factor!("ret20", "20日收益率", Momentum, Formula::Ret(20), 21),
        factor!("ret60", "60日收益率", Momentum, Formula::Ret(60), 61),
        factor!("sr5", "夏普比(5)", Momentum, Formula::Sr(5), 6),
        factor!("sr20", "夏普比(20)", Momentum, Formula::Sr(20), 21),
        factor!("sr60", "夏普比(60)", Momentum, Formula::Sr(60), 61),
        factor!("rs5", "相对强度(5)", Momentum, Formula::Rs(5), 5),
        factor!("rs10", "相对强度(10)", Momentum, Formula::Rs(10), 10),
        factor!("rs20", "相对强度(20)", Momentum, Formula::Rs(20), 20),
        factor!("rs60", "相对强度(60)", Momentum, Formula::Rs(60), 60),
        factor!("high_dist5", "距高点(5)", Momentum, Formula::HighDist(5), 5),
        factor!("high_dist10", "距高点(10)", Momentum, Formula::HighDist(10), 10),
        factor!("high_dist20", "距高点(20)", Momentum, Formula::HighDist(20), 20),
        factor!("low_dist5", "距低点(5)", Momentum, Formula::LowDist(5), 5),
        factor!("low_dist10", "距低点(10)", Momentum, Formula::LowDist(10), 10),
        factor!("low_dist20", "距低点(20)", Momentum, Formula::LowDist(20), 20),
        factor!("mom_div5", "动量背离(5)", Momentum, Formula::MomDiv(5), 20),
        factor!("mom_div20", "动量背离(20)", Momentum, Formula::MomDiv(20), 80),
        factor!("roc5", "变化率(5)", Momentum, Formula::Roc(5), 5),
        factor!("roc10", "变化率(10)", Momentum, Formula::Roc(10), 10),
        factor!("roc20", "变化率(20)", Momentum, Formula::Roc(20), 20),
        factor!("ltm_ratio", "长短期动量比", Momentum, Formula::LtmRatio, 60),
        factor!("pct_rank5", "分位排名(5)", Momentum, Formula::PctRank(5), 5),
        factor!("pct_rank20", "分位排名(20)", Momentum, Formula::PctRank(20), 20),
        factor!("ret_ma5", "收益均线(5)", Momentum, Formula::Ret(5), 6),
        factor!("ret_ma20", "收益均线(20)", Momentum, Formula::Ret(20), 21),

        // ═══════════════════ 流动性类 (Liquidity) 24个 ═══════════════════
        factor!("turn5", "换手率偏离(5)", Liquidity, Formula::Turn(5), 5),
        factor!("turn10", "换手率偏离(10)", Liquidity, Formula::Turn(10), 10),
        factor!("turn20", "换手率偏离(20)", Liquidity, Formula::Turn(20), 20),
        factor!("turn_std5", "换手率波动(5)", Liquidity, Formula::TurnStd(5), 5),
        factor!("turn_std20", "换手率波动(20)", Liquidity, Formula::TurnStd(20), 20),
        factor!("amihud5", "Amihud非流动性(5)", Liquidity, Formula::Amihud(5), 5),
        factor!("amihud20", "Amihud非流动性(20)", Liquidity, Formula::Amihud(20), 20),
        factor!("dollar_vol5", "成交额对数(5)", Liquidity, Formula::DollarVol(5), 5),
        factor!("dollar_vol20", "成交额对数(20)", Liquidity, Formula::DollarVol(20), 20),
        factor!("spread5", "价差(5)", Liquidity, Formula::Spread(5), 5),
        factor!("spread20", "价差(20)", Liquidity, Formula::Spread(20), 20),
        factor!("vwp5", "量价偏离(5)", Liquidity, Formula::Vwp(5), 5),
        factor!("vwp20", "量价偏离(20)", Liquidity, Formula::Vwp(20), 20),
        factor!("vol_conc5", "量集中度(5)", Liquidity, Formula::VolConc(5), 5),
        factor!("vol_conc20", "量集中度(20)", Liquidity, Formula::VolConc(20), 20),
        factor!("liq_ratio5", "流动性比(5)", Liquidity, Formula::LiqRatio(5), 5),
        factor!("liq_ratio20", "流动性比(20)", Liquidity, Formula::LiqRatio(20), 20),
        factor!("price_impact5", "价格冲击(5)", Liquidity, Formula::PriceImpact(5), 5),
        factor!("price_impact20", "价格冲击(20)", Liquidity, Formula::PriceImpact(20), 20),
        factor!("vol_break5", "放量突破(5)", Liquidity, Formula::VolBreak(5), 5),
        factor!("vol_break20", "放量突破(20)", Liquidity, Formula::VolBreak(20), 20),
        factor!("float_proxy", "流通市值代理", Liquidity, Formula::FloatProxy, 2),
        factor!("illiq_std5", "非流动性波动(5)", Liquidity, Formula::IlliqStd(5), 5),
        factor!("illiq_std20", "非流动性波动(20)", Liquidity, Formula::IlliqStd(20), 20),
    ]
}

pub fn find_by_name(name: &str) -> Option<FactorMeta> {
    list_all().into_iter().find(|f| f.name == name)
}
